### ISSUE TITLE
Issue with check_ephemeral_port_exhaustion.sh

### ISSUE THREAD

**Issue by pfilbin90** [bdossantos/nagios-plugins#15]
Hello,
Can you tell me why I cannot run this script from the nagios server to a remote host with the -H flag?
![untitled](https://user-images.githubusercontent.com/20479122/45115748-619ee400-b116-11e8-8f42-9b5efc6280e0.jpeg)

**Comment by bdossantos** [comment]
Hi!

Sorry, it was a mistake (probably due a bad copy/paste). Fixed there https://github.com/bdossantos/nagios-plugins/commit/60920f7edd57eef901bf4cfbb7464d6632e3c54d

**Comment by pfilbin90** [comment]
Okay,
So can this not be run on a remote host? Also, I'm unfortunately needing this check for a windows host but I see that this would not work on windows.  Do you have one that I can use with windows and Nagios?

**Comment by bdossantos** [comment]
Unfortunately this check is not designed to run on Windows :-( , but it work on Linux and probably on variants.
